---
title: "cm104 Notes and Exercises"
author: "Amanda Cheung"
date: "11/2/2017"
output: html_document
---
```{r}
library(repurrrsive)
library(listviewer)
library(jsonlite)
library(dplyr)
library(tibble)
library(purrr)
```

```{r}
View(gh_users)
View(gh_repos)
```

### Warm up and refresh challenge
Extract information from lists: name of second repo
```{r}
gh_repos %>%
  map_chr(list(2, "name"))
```

Extract information from lists: full name of first repo
```{r}
gh_repos %>%
  map_chr(list(1, "full_name"))

gh_repos %>%
  map_chr(list(1,3))
```

Extract information from lists: owner ID of fourth repo for each user
```{r}
gh_repos %>%
  map_int(list(4,4,2))

gh_repos %>%
  map_int(list(4, "owner", "id"))
```

```{r}
u_id <- gh_repos %>%
  map_int(list(1, "owner", "id"))

gh_repos_names <- gh_repos %>%
  set_names(u_id)

str(gh_repos_names, max.level = 1)

gh_repos_df <- gh_repos_names %>%
  enframe("user_id", "repository_stuff")

gh_repos_df
```

Try the same activity but use login instead of user_id
```{r}
login1 <- gh_repos %>%
  map_chr(list(1, "owner", "login"))

gh_repos_login <- gh_repos %>%
  set_names(login1)

gh_repos_df2 <- gh_repos_login %>%
  enframe("login", "repository_info")

gh_repos_df2
```


```{r}
gh_repos_df2 %>%
  filter(login1 %in% c("masalmon", "leeper")) %>% 
  mutate(number_of_repos = length(repository_info)) ## simply measures top level info


gh_repos_df2 %>%
  filter(login1 %in% c("masalmon", "leeper")) %>% 
  mutate(number_of_repos = map_int(repository_info, length))
```

```{r}
aliases_named <- set_names(map(got_chars, "aliases"), map(got_chars, "name"))

length(aliases_named) ## number of elements in the list

map_int(aliases_named, length) ## length of each list inside the list
```

```{r}
collapse_by_comma <- function(vec_of_strings){
  paste(vec_of_strings, collapse = ", ")
}

collapse_by_comma(c("first string", "second string"))
```

Take each element of our list and apply a function
```{r}
## 4 different methods
map(aliases_named, collapse_by_comma)
map(aliases_named,
    function(v_o_s) paste(v_o_s, collapse = ", "))
map(aliases_named, paste, collapse = ", ")
map(aliases_named, ~ paste(.x, collapse = ", "))
```














